### ISSUE TITLE
download U30

### ISSUE THREAD

**Issue by texrg** [hobiseven/Marlin_2.0.X_Beta_Alfawise_Ux0#11]
Is posible to put instruction and binary for U30 printer directle?
I dont know how compiling this

**Comment by hobiseven** [comment]
Compiling this : Just go to Marlin website please. This is using the regular Marlin 2 Platformio environement. 
Regarding binaries : Please have a look there : 

https://drive.google.com/drive/folders/1LgXFysFZxmHntWqbnIUsPiWBWq_f7pz5

Regarding loading the binay : Just copy project.bin to a blank SD card, put it in the SD slot, and power up the machine. Easy right?
